version: "3.8"

services:
  db:
    image: mysql/mysql-server:8.0
    container_name: mysql_s3_explorer
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: s3_explorer_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_s3_explorer
    ports:
      - "8090:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: s3_explorer_db
      DATABASE_USER: root
      DATABASE_PASSWORD: mysecretpassword
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_s3_explorer
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - app_network
    environment:
      REACT_APP_DJANGO_API_URL: http://localhost:8090

  minio:
    image: minio/minio:latest
    container_name: minio_s3_explorer
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000" # MinIO API port
      - "9001:9001" # MinIO Console port
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - app_network
    restart: unless-stopped

volumes:
  db_data:
  minio_data:

networks:
  app_network:
    driver: bridge
